<a href="https://colab.research.google.com/github/pradeeepta/ML/blob/main/PES1UG23CS819_Pradeepta_Panda_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 43.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 29.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 63.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 835.5 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 11.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 6.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 7.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# **Tensors**

Tensor Creation

In [2]:
import torch

In [3]:
#Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [4]:
# From Numpy array
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


In [5]:
# From other tensors
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7125, 0.9305],
        [0.9812, 0.6456]]) 



In [6]:
# Populating tensors with random/constant values

shape = (2, 3,) # tuple of tensor dimensions
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
torch.manual_seed(1789)
rand_tensor = torch.rand(shape)
empty_tensor = torch.empty(shape) # memory is allocated, tensor populated with garbage- values
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")
print(f"Empty Tensor: \n {empty_tensor}")


Random Tensor: 
 tensor([[0.9631, 0.4014, 0.7564],
        [0.5782, 0.5438, 0.1929]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Empty Tensor: 
 tensor([[4.6903e+01, 4.5495e-41, 4.6903e+01],
        [4.5495e-41, 4.3818e+11, 4.5493e-41]])


# **Tensor** **Attributes**

1.Shape

In [7]:
x = torch.empty(2, 2, 3)
print(x.shape,"\n")
print(x)


torch.Size([2, 2, 3]) 

tensor([[[4.6904e+01, 4.5495e-41, 3.4376e+27],
         [3.2800e-41, 3.4373e+27, 3.2800e-41]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 3.4387e+27, 3.2800e-41]]])


2.DataType

In [8]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.float64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int8)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int32)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.bool)
print(a.dtype)


torch.int16
torch.float64
torch.int8
torch.int32
torch.int64
torch.bool


3.Device

In [9]:
# Create a tensor
tensor = torch.rand(3, 2)
print(f"Device tensor is initially stored on: {tensor.device}")



Device tensor is initially stored on: cpu


# **Operations on** **Tensor**

In [10]:
# Check if GPU is available and move tensor to GPU if it is
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is now stored on: {tensor.device}")
else:
    print("CUDA is not available. Tensor remains on CPU.")

CUDA is not available. Tensor remains on CPU.


**Numpy-like Indexing and Slicing**

In [11]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}","\n")
print(f"First column: {tensor[:, 0]}","\n")
print(f"Last column: {tensor[:, -1]}","\n")
tensor[:,1] = 0 # set all elements in second column to 0
print(tensor)


First row: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1., 1.]) 

Last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Arithmetic operations

In [12]:
ones = torch.zeros(2, 2) + 1 # adding 1 to a tensor of zeros
twos = torch.ones(2, 2) * 2 # multiplying a tensor of ones by 2
threes = (torch.ones(2, 2) * 7 - 1) / 2 # chaining operations
fours = twos ** 2 # squaring a tensor
sqrt2s = twos ** 0.5 # square root of a tensor

print(ones,"\n")
print(twos,"\n")
print(threes,"\n")
print(fours,"\n")
print(sqrt2s,"\n")





tensor([[1., 1.],
        [1., 1.]]) 

tensor([[2., 2.],
        [2., 2.]]) 

tensor([[3., 3.],
        [3., 3.]]) 

tensor([[4., 4.],
        [4., 4.]]) 

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]]) 




Similar operations can be performed between two tensors:

In [13]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]]) # element-wise exponentiation
print(powers2,"\n")
fives = ones + fours # element-wise addition
print(fives,"\n")
dozens = threes * fours # element-wise multiplication
print(dozens,"\n")

tensor([[ 2.,  4.],
        [ 8., 16.]]) 

tensor([[5., 5.],
        [5., 5.]]) 

tensor([[12., 12.],
        [12., 12.]]) 



Tensor Broadcasting

In [14]:
rand = torch.rand(2, 4) # random tensor
doubled = rand * (torch.ones(1, 4) * 2) # broadcasting
print(rand)
print(doubled)


tensor([[0.2569, 0.8153, 0.3774, 0.6209],
        [0.8973, 0.6783, 0.8594, 0.6721]])
tensor([[0.5138, 1.6306, 0.7549, 1.2419],
        [1.7946, 1.3567, 1.7187, 1.3442]])


In [15]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(3, 2)
print(b, "\n") # 3rd & 2nd dims identical to a, dim 1 absent
c = a * torch.rand(4, 1, 2)
print(c, "\n") # 3rd dim = 1, 2nd dim identical to a
d = a * torch.rand(1, 3, 2)
print(d, "\n") # 3rd dim identical to a, 2nd dim = 1


tensor([[[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]]]) 

tensor([[[0.4606, 0.7056],
         [0.4606, 0.7056],
         [0.4606, 0.7056]],

        [[0.5921, 0.0557],
         [0.5921, 0.0557],
         [0.5921, 0.0557]],

        [[0.3866, 0.2989],
         [0.3866, 0.2989],
         [0.3866, 0.2989]],

        [[0.8993, 0.2320],
         [0.8993, 0.2320],
         [0.8993, 0.2320]]]) 

tensor([[[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]]]) 

# Common Functions

 **Mathematical Functions**

In [16]:
import math

a = torch.rand(2, 4) * 2 - 1 # random tensor in range [-1, 1]
print(torch.abs(a),"\n") #absolute value
print(torch.ceil(a),"\n") #ceiling
print(torch.floor(a),"\n") #floor
print(torch.clamp(a, -0.5, 0.5)) #clamping: values < -0.5 set to -0.5, values > 0.5 set to 0.5


tensor([[0.8933, 0.1511, 0.7021, 0.4549],
        [0.2857, 0.2995, 0.6397, 0.6817]]) 

tensor([[-0., -0., -0., -0.],
        [1., -0., 1., -0.]]) 

tensor([[-1., -1., -1., -1.],
        [ 0., -1.,  0., -1.]]) 

tensor([[-0.5000, -0.1511, -0.5000, -0.4549],
        [ 0.2857, -0.2995,  0.5000, -0.5000]])



 **Trigonometric Functions and Their Inverses**

In [ ]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4]) # angles in radians
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles,"\n")
print(sines,"\n")
print(inverses,"\n")


Bitwise **Operations**

In [17]:
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


tensor([3, 2, 1])


**Comparisons**

In [18]:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
print(d,"\n")
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(e,"\n")
print(torch.eq(d, e))  # returns a tensor of type bool



Broadcasted, element-wise equality comparison:
tensor([[1., 2.],
        [3., 4.]]) 

tensor([[1., 1.]]) 

tensor([[ True, False],
        [False, False]])


**Reductions**

In [19]:
d = torch.tensor([[1., 2.], [3., 4.]])
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))  # filter unique elements


tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


**Vector and Linear Algebra Operations**

In [21]:
import torch

v1 = torch.tensor([1., 0., 0.])  # x unit vector
v2 = torch.tensor([0., 1., 0.])  # y unit vector

# Specify dim=0 to avoid the warning
print(torch.cross(v1, v2, dim=0), "\n")  # returns cross product of vectors v1 and v2

m1 = torch.rand(2, 2)  # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]])  # three times identity matrix
print(m1, "\n")

m3 = torch.matmul(m1, m2)  # same as m3 = m1@m2
print(m3, "\n")

print(torch.svd(m3), "\n")  # singular value decomposition


tensor([0., 0., 1.]) 

tensor([[0.5300, 0.3159],
        [0.7081, 0.1727]]) 

tensor([[1.5900, 0.9478],
        [2.1244, 0.5181]]) 

torch.return_types.svd(
U=tensor([[-0.6432, -0.7657],
        [-0.7657,  0.6432]]),
S=tensor([2.8340, 0.4198]),
V=tensor([[-0.9348,  0.3551],
        [-0.3551, -0.9348]])) 



# Altering Tensors in Place

In [22]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))  # this operation creates a new tensor in memory
print(a)  # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)  # b has changed


a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


**For Arithmetic Operations:**

In [23]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)
print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)


Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9051, 0.5988],
        [0.2455, 0.1117]])

After adding:
tensor([[1.9051, 1.5988],
        [1.2455, 1.1117]])
tensor([[1.9051, 1.5988],
        [1.2455, 1.1117]])
tensor([[0.9051, 0.5988],
        [0.2455, 0.1117]])

After multiplying
tensor([[0.8192, 0.3585],
        [0.0603, 0.0125]])
tensor([[0.8192, 0.3585],
        [0.0603, 0.0125]])


In [24]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)
print(c,"\n")
d = torch.matmul(a, b, out=c)
print(c,"\n") # contents of c have changed

assert c is d # test c & d are same object, not just containing equal values # make sure that our new c is the same object as the old one
assert id(c) == old_id

torch.rand(2, 2, out=c) # works for creation too!
print(c,"\n") # c has changed again

assert id(c) == old_id # still the same object!






tensor([[0., 0.],
        [0., 0.]]) 

tensor([[0.2817, 0.2602],
        [0.7920, 0.7133]]) 

tensor([[0.2893, 0.1629],
        [0.1285, 0.9058]]) 



**Manipulating Tensor Shape**

In [25]:
a = torch.tensor([1, 2, 3, 4])
a_reshaped = torch.reshape(a, (2, 2))
print(a_reshaped,"\n")

b = torch.rand(56, 56)  # Consider 56x56 image
c = b.unsqueeze(0)  # unsqueeze(i) adds dimension of length 1 at index i
print(c,"\n")  # c is now a batch of 1 image of shape 56x56

d = torch.rand(1, 20)
print(d.shape,"\n")
e = d.squeeze(0)  # squeeze(i) removes a dimension if shape[i] is 1
print(e.shape,"\n")

x, y, z = torch.rand(2, 3), torch.rand(2, 3), torch.rand(2, 3)
cat_tensor = torch.cat((x, y, z), dim=0)  # concatenates tensors along rows
print(cat_tensor)


tensor([[1, 2],
        [3, 4]]) 

tensor([[[0.3869, 0.3910, 0.6414,  ..., 0.6620, 0.0410, 0.4947],
         [0.4832, 0.0296, 0.9237,  ..., 0.9733, 0.3692, 0.1148],
         [0.3430, 0.5337, 0.8697,  ..., 0.3805, 0.9086, 0.1219],
         ...,
         [0.5783, 0.1764, 0.5656,  ..., 0.3075, 0.0482, 0.2547],
         [0.8921, 0.2354, 0.8930,  ..., 0.9426, 0.9898, 0.3402],
         [0.9503, 0.2805, 0.7728,  ..., 0.6669, 0.6923, 0.6081]]]) 

torch.Size([1, 20]) 

torch.Size([20]) 

tensor([[0.9595, 0.6804, 0.7525],
        [0.3462, 0.6816, 0.7475],
        [0.8048, 0.6805, 0.6754],
        [0.7080, 0.1422, 0.7200],
        [0.5164, 0.3350, 0.1107],
        [0.1027, 0.5759, 0.5720]])


**Copying Tensors**

In [26]:
a = torch.ones(2, 2)
b=a
a[0][1] = 561 # we change a...
print(b) # ...and b is also altered


tensor([[  1., 561.],
        [  1.,   1.]])


In [27]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # different objects in memory...
print(torch.eq(a,b)) # ...but still with the same contents!
a[0][1] = 561 # a changes...
print(b)   # ...but b is still all ones






tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


# Moving to GPU

In [28]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    try:
        device = torch.device("mps")
        print("MPS available!")
    except:
        print('Sorry, CPU only.')


MPS available!


In [30]:
import torch

if torch.cuda.is_available():
    my_device = torch.device('cuda')
elif torch.backends.mps.is_available():
    try:
        my_device = torch.device("mps")
    except Exception as e:
        print(f"MPS is available but encountered an issue: {e}")
        my_device = torch.device('cpu')
else:
    my_device = torch.device('cpu')

# Try to create the tensor and handle potential issues with MPS
try:
    x = torch.rand(2, 2, device=my_device)
    print(x)
except NotImplementedError as e:
    print(f"Operation not supported on {my_device}, falling back to CPU. Error: {e}")
    my_device = torch.device('cpu')
    x = torch.rand(2, 2, device=my_device)
    print(x)


tensor([[0.0948, 0.9340],
        [0.8146, 0.6878]])


In [31]:
y = torch.rand(2, 2)
y = y.to(my_device)


# Numpy Bridge

In [32]:
import numpy as np
import torch

# Creating a NumPy array
numpy_array = np.ones((2, 3))
print("NumPy Array:")
print(numpy_array)

# Converting NumPy array to PyTorch tensor
pytorch_tensor = torch.from_numpy(numpy_array)
print("\nPyTorch Tensor:")
print(pytorch_tensor)

# Creating a random PyTorch tensor
pytorch_rand = torch.rand(2, 3)
print("\nRandom PyTorch Tensor:")
print(pytorch_rand)

# Converting PyTorch tensor to NumPy array
numpy_rand = pytorch_rand.numpy()
print("\nConverted NumPy Array:")
print(numpy_rand)

# Changes to NumPy array reflect in the PyTorch tensor and vice versa
numpy_array[1, 1] = 23
print("\nUpdated PyTorch Tensor from NumPy Array:")
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print("\nUpdated NumPy Array from PyTorch Tensor:")
print(numpy_rand)


NumPy Array:
[[1. 1. 1.]
 [1. 1. 1.]]

PyTorch Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Random PyTorch Tensor:
tensor([[0.0657, 0.6053, 0.7513],
        [0.3740, 0.3623, 0.2364]])

Converted NumPy Array:
[[0.06566584 0.6053149  0.75132155]
 [0.3739767  0.36231697 0.23642415]]

Updated PyTorch Tensor from NumPy Array:
tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)

Updated NumPy Array from PyTorch Tensor:
[[ 0.06566584  0.6053149   0.75132155]
 [ 0.3739767  17.          0.23642415]]


In [33]:
numpy_array[1, 1] = 23
print(pytorch_tensor,"\n")
pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64) 

[[ 0.06566584  0.6053149   0.75132155]
 [ 0.3739767  17.          0.23642415]]


# Questions

**1.Obtain a tensor containing only zeroes from the given tensor**

In [34]:
pattern = torch.tensor([
    [1, 1, 1, 1],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 1, 1, 1]
])

**2.Create a Numpy array of shape (1,3,3) using PyTorch**

In [35]:
# Create a PyTorch tensor of shape (1, 3, 3)
tensor = torch.rand(1, 3, 3)

# Convert the PyTorch tensor to a NumPy array
numpy_array = tensor.numpy()

print(numpy_array)
print(numpy_array.shape)

[[[0.91326284 0.66957337 0.69045967]
  [0.7940236  0.9694786  0.3223291 ]
  [0.22728765 0.11060762 0.039702  ]]]
(1, 3, 3)


**3.Create two random (2,2,2) tensors and find the max, min, mean, std of their product (matrix multiplication)**

In [36]:
import numpy as np

# Step 1: Create two random (2,2,2) tensors
tensor1 = np.random.rand(2, 2, 2)
tensor2 = np.random.rand(2, 2, 2)

# Step 2: Perform matrix multiplication
result_tensor = np.array([np.matmul(tensor1[i], tensor2[i]) for i in range(2)])

# Flatten the result tensor to compute statistics
flattened_result = result_tensor.flatten()

# Step 3: Compute statistics
max_value = np.max(flattened_result)
min_value = np.min(flattened_result)
mean_value = np.mean(flattened_result)
std_value = np.std(flattened_result)

max_value, min_value, mean_value, std_value


(0.8513975949925369,
 0.1721895145844294,
 0.4985032699227055,
 0.20700699761447994)

**Convert a 16x16 tensor into 1x256 tensor**

In [37]:
import numpy as np

# Create a random 16x16 tensor
tensor = np.random.rand(16, 16)

# Flatten the tensor to 1x256
flattened_tensor = tensor.flatten().reshape(1, 256)

print("Flattened Tensor Shape:", flattened_tensor.shape)
print(flattened_tensor)


Flattened Tensor Shape: (1, 256)
[[0.07323279 0.22197142 0.15565212 0.70231586 0.22719002 0.32426555
  0.18944969 0.91959399 0.9371159  0.02631184 0.18588095 0.27160856
  0.66612932 0.82438139 0.04121301 0.96633816 0.76474995 0.25888416
  0.29541691 0.20507255 0.28495448 0.6572825  0.14166796 0.29020411
  0.88787394 0.89450302 0.26266661 0.15873283 0.3582382  0.63293882
  0.00594315 0.4151521  0.69432599 0.88953629 0.356736   0.27681136
  0.81912481 0.24279783 0.73364988 0.76197525 0.13122814 0.41442325
  0.67985332 0.82467003 0.37825424 0.10101755 0.15952356 0.0226329
  0.25829473 0.56097405 0.14775757 0.07793155 0.45330622 0.31844693
  0.43023977 0.68545629 0.85553692 0.23645363 0.43719875 0.79939056
  0.46587527 0.18793531 0.15849454 0.03269066 0.04072185 0.79212631
  0.53489219 0.53392514 0.12140026 0.09393459 0.83360112 0.89077157
  0.47579444 0.94834505 0.40390337 0.3663254  0.57808102 0.06469804
  0.04807491 0.82010251 0.00160531 0.43750202 0.72305546 0.34597247
  0.89362948 0.3


**Given two tensors x and Y, find the coefficients that best model the linear relationship Y = ax + b (Linear Regression)**


In [38]:
import numpy as np

# Example tensors
x = np.array([1, 2, 3, 4, 5])  # Replace with your tensor x
Y = np.array([2, 4, 6, 8, 10])  # Replace with your tensor Y

# Step 1: Create the design matrix X
X = np.vstack([x, np.ones_like(x)]).T

# Step 2: Compute the coefficients using the normal equation
# theta = (X^T X)^(-1) X^T Y
theta = np.linalg.inv(X.T @ X) @ X.T @ Y

# Extract the coefficients
a, b = theta

print("Coefficient a:", a)
print("Intercept b:", b)


Coefficient a: 1.9999999999999996
Intercept b: 4.884981308350689e-15
